name:                algebraic-json
version:             0.1.0.0
github:              "luochen1990/algebraic-json"
license:             Apache-2.0
author:              "LuoChen"
maintainer:          "luochen1990@gmail.com"
copyright:           "2018 LuoChen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/luochen1990/algebraic-json#README.md>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- hspec
- QuickCheck
- data-fix
- bytes
- cereal
- bytestring

library:
  source-dirs: src

executables:
  algebraic-json-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algebraic-json

tests:
  algebraic-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algebraic-json
